In [52]:
#Data Set name crop_yield_data(in).csv

In [53]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [54]:
import pandas as pd
df = pd.read_csv("crop_yield_data(in).csv")
df

temperature  humidity  rainfall  soil_quality  fertilizer_used  crop_yield
0           25        60        50             7              200        2000
1           28        65        60             6              220        2200
2           24        58        40             8              180        1800
3           26        62        55             7              210        2100
4           22        59        45             6              190        1900
5           30        70        70             7              250        2500
6           23        64        65             6              240        2300
7           27        63        50             8              200        2200
8           29        68        75             7              230        2400
9           25        60        55             6              210        2100

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   temperature      10 non-null     int64
 1   humidity         10 non-null     int64
 2   rainfall         10 non-null     int64
 3   soil_quality     10 non-null     int64
 4   fertilizer_used  10 non-null     int64
 5   crop_yield       10 non-null     int64
dtypes: int64(6)
memory usage: 612.0 bytes


In [56]:
df.columns

Index(['temperature', 'humidity', 'rainfall', 'soil_quality',
       'fertilizer_used', 'crop_yield'],
      dtype='object')

In [57]:

X = df[['temperature', 'humidity', 'rainfall', 'soil_quality',
       'fertilizer_used']]
y = df['crop_yield']



In [58]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

y_scaled = scaler.fit_transform(y.values.reshape(-1, 1))
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_scaled, test_size=0.2, random_state=42)

model = keras.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

model.fit(X_train, y_train, epochs=50, batch_size=16, validation_data=(X_test, y_test))

loss, mae = model.evaluate(X_test, y_test)
print(f"Test MAE: {mae}")




Epoch 1/50


C:\Users\NICE\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.5744 - mae: 0.6057 - val_loss: 0.3037 - val_mae: 0.4958
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - loss: 0.5054 - mae: 0.5724 - val_loss: 0.2569 - val_mae: 0.4550
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - loss: 0.4423 - mae: 0.5395 - val_loss: 0.2136 - val_mae: 0.4134
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - loss: 0.3840 - mae: 0.5064 - val_loss: 0.1741 - val_mae: 0.3713
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - loss: 0.3317 - mae: 0.4739 - val_loss: 0.1384 - val_mae: 0.3288
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - loss: 0.2854 - mae: 0.4422 - val_loss: 0.1070 - val_mae: 0.2868
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - loss: 0.2441 - mae: 0.4110 - val_loss: 0.0793 - val_mae: 0.2450
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 0.2061 - mae: 0.3795 - val_loss: 0.0557 - val_mae: 0.2032
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 0.1722 - mae: 0.3478 - val_lo

In [59]:
y_pred = model.predict(X_test)
y_pred


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step


array([[1.5180378 ],
       [0.46226782]], dtype=float32)

In [60]:
y_test

array([[1.21267813],
       [0.24253563]])

In [61]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                     │ (None, 64)                  │             384 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_13 (Dense)                     │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_14 (Dense)                     │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 7,493 (29.27 KB)

 Trainable params: 2,497 (9.75 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 4,996 (19.52 KB)

In [62]:
loss = model.evaluate(X_test, y_test)
print(loss)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0708 - mae: 0.2625
[0.07076339423656464, 0.26254594326019287]


In [63]:
# data set name climate_data(in).csv

In [67]:
import pandas as pd
df = pd.read_csv("climate_data(in).csv")
df.head()

Temperature   Humidity    Rainfall  Wind Speed  Solar Radiation  \
0    26.236204  46.154857  145.999662   12.762891         3.793472   
1    43.521429  43.303847   36.902399    9.185849         2.568907   
2    36.959818  32.330774   69.327939   19.289970         2.758155   
3    32.959755  62.508667  132.656127    4.379569         3.084027   
4    19.680559  53.363691   96.417869   11.757128         3.221920   

      Pressure  Population Density  Industrial Activity Index  Green Cover  \
0  1034.723658         7441.396511                   0.042661    67.271512   
1   999.451704         8822.908563                   0.828505    20.168883   
2   969.546561         4685.480766                   0.249308    76.252466   
3  1023.664179         2962.869444                   0.283937    69.025688   
4   991.867814         3256.581086                   0.226245    74.319731   

   Air Quality Index  Energy Consumption  
0         269.289789         2254.722860  
1         276.793110         2694.385935  
2         144.593080         1423.674455  
3         107.907681          883.981472  
4          97.915263         1001.712463

In [68]:
df.isna().sum()

Temperature                  0
Humidity                     0
Rainfall                     0
Wind Speed                   0
Solar Radiation              0
Pressure                     0
Population Density           0
Industrial Activity Index    0
Green Cover                  0
Air Quality Index            0
Energy Consumption           0
dtype: int64

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Temperature                10000 non-null  float64
 1   Humidity                   10000 non-null  float64
 2   Rainfall                   10000 non-null  float64
 3   Wind Speed                 10000 non-null  float64
 4   Solar Radiation            10000 non-null  float64
 5   Pressure                   10000 non-null  float64
 6   Population Density         10000 non-null  float64
 7   Industrial Activity Index  10000 non-null  float64
 8   Green Cover                10000 non-null  float64
 9   Air Quality Index          10000 non-null  float64
 10  Energy Consumption         10000 non-null  float64
dtypes: float64(11)
memory usage: 859.5 KB


In [70]:
df.columns

Index(['Temperature', 'Humidity', 'Rainfall', 'Wind Speed', 'Solar Radiation',
       'Pressure', 'Population Density', 'Industrial Activity Index',
       'Green Cover', 'Air Quality Index', 'Energy Consumption'],
      dtype='object')

In [71]:
X = df[['Temperature', 'Humidity', 'Rainfall', 'Wind Speed', 'Solar Radiation',
       'Pressure', 'Population Density', 'Industrial Activity Index',
       'Green Cover', 'Air Quality Index']]
y = df['Energy Consumption']

In [72]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

y_scaled = scaler.fit_transform(y.values.reshape(-1, 1))
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_scaled, test_size=0.2, random_state=42)

model = keras.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

model.fit(X_train, y_train, epochs=50, batch_size=16, validation_data=(X_test, y_test))

loss, mae = model.evaluate(X_test, y_test)
print(f"Test MAE: {mae}")




Epoch 1/50


C:\Users\NICE\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3847 - mae: 0.3962 - val_loss: 0.0097 - val_mae: 0.0777
Epoch 2/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0076 - mae: 0.0685 - val_loss: 0.0058 - val_mae: 0.0603
Epoch 3/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0046 - mae: 0.0531 - val_loss: 0.0043 - val_mae: 0.0524
Epoch 4/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0031 - mae: 0.0440 - val_loss: 0.0026 - val_mae: 0.0405
Epoch 5/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0021 - mae: 0.0368 - val_loss: 0.0022 - val_mae: 0.0370
Epoch 6/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0016 - mae: 0.0315 - val_loss: 0.0013 - val_mae: 0.0291
Epoch 7/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0012 - mae: 0.0274 - val_loss: 0.0011 - val_mae: 0.0263
Epoch 8/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.8559e-04 - mae: 0.0236 - val_loss: 7.0113e-04 - val_mae: 0.0209
Epoch 9/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss:

In [73]:
y_pred = model.predict(X_test)
y_pred


63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([[-0.431587  ],
       [ 0.9405713 ],
       [-1.5481865 ],
       ...,
       [-0.27173695],
       [ 1.0994513 ],
       [ 0.63231903]], dtype=float32)

In [74]:
y_test

array([[-0.45360272],
       [ 0.92755075],
       [-1.54789913],
       ...,
       [-0.27728912],
       [ 1.09882073],
       [ 0.6277934 ]])

In [76]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_15 (Dense)                     │ (None, 64)                  │             704 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_16 (Dense)                     │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_17 (Dense)                     │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 8,453 (33.02 KB)

 Trainable params: 2,817 (11.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 5,636 (22.02 KB)

In [77]:
from sklearn.metrics import r2_score

# Compute R-squared score
r2 = r2_score(y_test, y_pred)
print(f"R-squared Score: {r2:.4f}")


R-squared Score: 0.9998
