In [7]:
#Creat a String variable store city name 
name = "Nagpur"
cf = 25.45
temp = 39
print(f"City {name},cf is  {cf},temp is {temp}")

City Nagpur,cf is  25.45,temp is 39


In [10]:
cf = int(input("Enter the cf of city "))
if cf <30:
    print("City is Sustainable")
else:
    print("City Not Sustainable")

Enter the cf of city  15


City is Sustainable


In [12]:
Weekly_temp = [25,36,45,55,65]
print(f"Weekly Temp {Weekly_temp }")

Weekly Temp [25, 36, 45, 55, 65]


In [15]:
#creat e dictionar 
city_data = {
    "name" : "Nagpur",
    "temp" : 25,
    "cf" : 66,
    "sus" : False
}
print(city_data)

{'name': 'Nagpur', 'temp': 25, 'cf': 66, 'sus': False}


In [16]:
5**5

3125

In [ ]:
climate_data = [
    {"city": "City A", "temperature": 25, "carbon_footprint": 500},
    {"city": "City B", "temperature": 30, "carbon_footprint": 350},
    {"city": "City C", "temperature": 22, "carbon_footprint": 600},
    {"city": "City D", "temperature": 15, "carbon_footprint": 200},
    {"city": "City E", "temperature": 28, "carbon_footprint": 450},
]


In [34]:
climate_data = [
    {"city": "City A", "temperature": 25, "carbon_footprint": 500},
    {"city": "City B", "temperature": 30, "carbon_footprint": 350},
    {"city": "City C", "temperature": 22, "carbon_footprint": 600},
    {"city": "City D", "temperature": 15, "carbon_footprint": 200},
    {"city": "City E", "temperature": 28, "carbon_footprint": 450},
]

# Ensure all spaces are normal by re-encoding
for data in climate_data:
    print(f"City: {data['city']}, Temperature: {data['temperature']}°C, Carbon Footprint: {data['carbon_footprint']} kg")


City: City A, Temperature: 25°C, Carbon Footprint: 500 kg
City: City B, Temperature: 30°C, Carbon Footprint: 350 kg
City: City C, Temperature: 22°C, Carbon Footprint: 600 kg
City: City D, Temperature: 15°C, Carbon Footprint: 200 kg
City: City E, Temperature: 28°C, Carbon Footprint: 450 kg


In [23]:
thresold_tem = 26
high_temp = [city for city in climate_data if city['temperature'] > thresold_tem ]
print(high_temp)

[{'city': 'City B', 'temperature': 30, 'carbon_footprint': 350}, {'city': 'City E', 'temperature': 28, 'carbon_footprint': 450}]


In [29]:
for city in high_temp:
    print(f"{city['city']} - {city ["temperature"]}")

City B - 30
City E - 28


In [36]:
total_carbon = 0
for city in climate_data:
    total_carbon += city["carbon_footprint"]  # Corrected key name
print(f"Total Carbon Footprint: {total_carbon} kg")  # Added a label for clarity


Total Carbon Footprint: 2100 kg


In [1]:
#Object Orientated Programing in python 

In [12]:
class carbon_tracker:
  def __init__(self , transport_mode, distance):
    self.transport_mode = transport_mode
    self.distance = distance

  def calculaate_emission(self):
    emission_factor = {"car":0.21,"bus":0.18,"cycle":0.0,"walk":0.0}
    # Corrected variable name from factor to emission_factor
    return self.distance * emission_factor.get(self.transport_mode,0.15)

  def alternate(self):
    if self.transport_mode == "car":
      return "bus"
    elif self.transport_mode == "bus":
      return "walk"
    else:
      return "car"

tracker = carbon_tracker("car",35)
tracker1= carbon_tracker("bus",105)
print(f"emission for {tracker.calculaate_emission()}kg Co2")
print(f"emission for {tracker1.calculaate_emission()}kg Co2")
print(f"alternate mode is {tracker.alternate()}")

emission for 7.35kg Co2
emission for 18.9kg Co2
alternate mode is bus


In [13]:
name of building 
energy consuption and emmision factor having attribute give me the code to calculate enery symstem for calculating carbon

SyntaxError: invalid syntax (3733266816.py, line 1)

In [20]:
class EnergyEmission:
    def __init__(self, building_name, energy_consumption, emission_factor):
        self.building_name = building_name
        self.energy_consumption = energy_consumption  
        self.emission_factor = emission_factor  

    def calculate_carbon_emission(self):
        return self.energy_consumption * self.emission_factor


building = EnergyEmission("Green Towers", 5000, 0.45)  
 
print(f"Carbon Emission for {building.building_name}: {building.calculate_carbon_emission()} Kg CO2")
print(building.calculate_carbon_emission())

Carbon Emission for Green Towers: 2250.0 Kg CO2
2250.0


In [32]:
class SolarSystemEmission:
    def __init__(self, building_name, energy_consumption, emission_factor, solar_energy):
        self.building_name = building_name
        self.energy_consumption = energy_consumption  
        self.emission_factor = emission_factor  
        self.solar_energy = solar_energy  

    def calculate_carbon_emission(self):
        return (self.energy_consumption * self.emission_factor) - self.solar_energy        


building = SolarSystemEmission("Green Towers", 5000, 0.45, 55)  

print(f"Carbon Emission for {building.building_name}: {building.calculate_carbon_emission()} Kg CO2")
print(building.calculate_carbon_emission())


Carbon Emission for Green Towers: 2195.0 Kg CO2
2195.0


In [33]:
'''Class Inheritance: Waste and PlasticWaste

Base class: Waste with attributes:

weight_kg

category (e.g., biodegradable, recyclable)


Subclass: PlasticWaste with additional attribute:

type_of_plastic (e.g., PET, HDPE)


Methods:

is_recyclable() – returns True or False based on plastic type'''


'Class Inheritance: Waste and PlasticWaste\n\nBase class: Waste with attributes:\n\nweight_kg\n\ncategory (e.g., biodegradable, recyclable)\n\n\nSubclass: PlasticWaste with additional attribute:\n\ntype_of_plastic (e.g., PET, HDPE)\n\n\nMethods:\n\nis_recyclable() – returns True or False based\xa0on\xa0plastic\xa0type'

In [39]:
class Waste:
    def __init__(self, weight_kg, category):
        self.weight_kg = weight_kg
        self.category = category

class PlasticWaste(Waste):
    def __init__(self, weight_kg, category, type_of_plastic):
        super().__init__(weight_kg, category)
        self.type_of_plastic = type_of_plastic

    def is_recyclable(self):
        recyclable_plastics = {"PET", "HDPE", "LDPE", "PP"}
        return self.type_of_plastic in recyclable_plastics


plastic_item = PlasticWaste(2, "recyclable", "HDPE")
print(f"Plastic Type: {plastic_item.type_of_plastic}")
print(f"Is recyclable? {plastic_item.is_recyclable()}")


Plastic Type: HDPE
Is recyclable? True


In [40]:
'''Class: WaterUsageMonitor

Track water usage by a household.

Include:

daily_usage (list of 7 values)

Method average_usage()

Method exceeds_limit() – checks against sustainable limit (e.g., 150 L/day)'''

'Class: WaterUsageMonitor\n\nTrack water usage by a household.\n\nInclude:\n\ndaily_usage (list of 7 values)\n\nMethod average_usage()\n\nMethod exceeds_limit() – checks against sustainable limit (e.g.,\xa0150\xa0L/day)'

In [47]:
class WaterUsageMonitor:
    def __init__(self, daily_usage):
        self.daily_usage = daily_usage  
        self.limit = 150  
        
    def average_usage(self):
        return sum(self.daily_usage) / 7  
    def exceeds_limit(self):
        return self.average_usage() > self.limit 


weekly_usage = [120, 145, 135, 160, 155, 145, 130]  
monitor = WaterUsageMonitor(weekly_usage)

print(f"Average Daily Usage: {monitor.average_usage()} L")
print(f"Exceeds Limit? {'Yes' if monitor.exceeds_limit() else 'No'}")


Average Daily Usage: 141.42857142857142 L
Exceeds Limit? No


In [4]:
array = ["s","d"]
print(array)
array.sort()
print(array+array )

['s', 'd']
['d', 's', 'd', 's']


In [1]:
list = ["Shubham",25,"Dubey"]
print(list)


['Shubham', 25, 'Dubey']


In [10]:
a = (1,2,3)
print(a)
v = a+a
print(v)

(1, 2, 3)
(1, 2, 3, 1, 2, 3)


In [12]:
dict = {
    "name" : "Shubham",
    "number" : 56
}
print(dict)

{'name': 'Shubham', 'number': 56}


In [27]:
array = [1,5,3,4,0]
array_2 = [1,5,3,4,0]
add= array+array_2
print(add)


[1, 5, 3, 4, 0, 1, 5, 3, 4, 0]


In [26]:
array_2 = [1,5,3,4,0]
a = array_2.index(0)
print(a)

4


In [31]:
array_2 = [1,5,3,4,0]
print(array_2 [1:4:2])

[5, 4]


In [6]:
add = lambda a,y : a+y
print(add(2,6))

8


In [37]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
split_parts = np.array_split(a, 3)  
print(split_parts)  


[array([1, 2]), array([3, 4]), array([5])]


In [49]:
print("Star")
for i in range (10):
    print(i*"a")

Star

a
aa
aaa
aaaa
aaaaa
aaaaaa
aaaaaaa
aaaaaaaa
aaaaaaaaa


In [53]:
print("Star")
for i in range (10,0,-1):
    print(i*"a")

Star
aaaaaaaaaa
aaaaaaaaa
aaaaaaaa
aaaaaaa
aaaaaa
aaaaa
aaaa
aaa
aa
a


In [58]:
v = "Shubham"
c =v[::-1]
print(c)

mahbuhS


In [59]:
print(a)

[1 2 3 4 5]


In [70]:
import numpy as np
arr = np.array([[1 ,2 ,3 ,4, 5],[1 ,2, 3 ,4, 5]])
print(arr)
print(arr.ndim)

[[1 2 3 4 5]
 [1 2 3 4 5]]
2


In [94]:
import numpy as np 
random_data = np.random.randint(10,50 , size = (4,10))
print(random_data)
print(random_data.ndim)

[[47 35 24 36 37 46 30 11 46 39]
 [40 27 48 40 49 37 30 11 33 14]
 [21 26 14 43 22 29 40 14 35 49]
 [15 14 11 41 20 17 34 43 37 14]]
2


In [95]:
random_data.min()

11

In [96]:
random_data.sum()

1219

In [97]:
random_data.std()

12.247423198371159

In [102]:
i = 0
for i in range(15):
    print(i*"*")


*
**
***
****
*****
******
*******
********
*********
**********
***********
************
*************
**************


In [104]:
i = 0
for i in range (15,0,-1):
    print(i*"*")

***************
**************
*************
************
***********
**********
*********
********
*******
******
*****
****
***
**
*


In [128]:
n = 10
for i in range (15):
    print("1" *n *i)


1111111111
11111111111111111111
111111111111111111111111111111
1111111111111111111111111111111111111111
11111111111111111111111111111111111111111111111111
111111111111111111111111111111111111111111111111111111111111
1111111111111111111111111111111111111111111111111111111111111111111111
11111111111111111111111111111111111111111111111111111111111111111111111111111111
111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
1111111111111111111111111111111111111111111111111111111111111111111111111111

In [129]:
print(random_data)


[[47 35 24 36 37 46 30 11 46 39]
 [40 27 48 40 49 37 30 11 33 14]
 [21 26 14 43 22 29 40 14 35 49]
 [15 14 11 41 20 17 34 43 37 14]]


In [136]:
random_data.sum(axis =1)

array([351, 329, 293, 246])

In [132]:
random_data.sum(axis =0)

array([123, 102,  97, 160, 128, 129, 134,  79, 151, 116])

In [134]:
random_data.argmax()

14

In [143]:
import numpy as np
a =np.array([0])
print(a.ndim,a)

1 [0]


In [142]:
import numpy as np

a = np.array(42)  
print(a.ndim)  
print(a)      


0
42


In [153]:
import numpy as np 
random_data = np.random.randint(10 ,50, size = 10)
random_data

array([44, 16, 16, 34, 19, 21, 22, 41, 21, 20])

In [157]:
random_data.mean()

25.4

In [160]:
below_20 = np.where(random_data>20) [0] +1
below_20

array([1, 4, 6, 7, 8, 9], dtype=int64)

In [161]:
random_data.max()

44

In [168]:
import numpy as np 
random_data = np.random.randint(10 ,50, size = (12,5))
random_data

array([[36, 31, 43, 12, 16],
       [25, 27, 10, 12, 48],
       [28, 25, 42, 38, 28],
       [37, 11, 40, 29, 49],
       [49, 36, 41, 19, 12],
       [19, 23, 35, 21, 41],
       [24, 29, 24, 33, 34],
       [37, 49, 38, 48, 33],
       [25, 42, 19, 23, 16],
       [48, 13, 32, 19, 31],
       [29, 17, 26, 36, 12],
       [22, 20, 24, 33, 13]])

In [170]:
ave = np.average(random_data)
ave

28.866666666666667

In [172]:
ave = np.where(random_data>20) [0] +1
ave

array([ 1,  1,  1,  2,  2,  2,  3,  3,  3,  3,  3,  4,  4,  4,  4,  5,  5,
        5,  6,  6,  6,  6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,
        9, 10, 10, 10, 11, 11, 11, 12, 12, 12], dtype=int64)

In [173]:
import numpy as np

water_usage = np.random.randint(5000, 20000, size=(12, 5))
print("Water Usage Data:\n", water_usage)

total_usage_per_field = np.sum(water_usage, axis=0)
print("Total Water Usage Per Field:\n", total_usage_per_field)

highest_usage_month = np.argmax(np.sum(water_usage, axis=1)) + 1
print("Month with Highest Water Usage:", highest_usage_month)

average_february_usage = np.average(water_usage[1])
print("Average Water Usage in February:", average_february_usage)

overall_avg_usage = np.average(water_usage)
print("Overall Average Water Usage:", overall_avg_usage)


Water Usage Data:
 [[18900  8573  5836 12704  5772]
 [ 7132  6734 17243  7039 12789]
 [18261 13727 16119 18617 14792]
 [18352 14937 16920 12051 13802]
 [ 5691 11033 17827 10376  7812]
 [ 6569 18497 16001  7614 16241]
 [18442 12810 13272 12055  8176]
 [16001 19973 17011 15337  9421]
 [15458  5727  5451 10143  8754]
 [ 7838 11560 19499  5795 17153]
 [ 7357 11673 11873 11366  7375]
 [14450  7760  7243 12943 18738]]
Total Water Usage Per Field:
 [154451 143004 164295 136040 140825]
Month with Highest Water Usage: 3
Average Water Usage in February: 10187.4
Overall Average Water Usage: 12310.25


In [174]:
#Pandas

In [185]:
import pandas as pd
data = {
    25,25,23,250,
    25,46,55
}
df=pd.DataFrame(data)
df

0
0   55
1   23
2   25
3  250
4   46

In [187]:
import pandas as pd
data = [
    25,25,23,250,
    25,46,55
]
df=pd.Series(data)
df

0     25
1     25
2     23
3    250
4     25
5     46
6     55
dtype: int64

In [190]:
import pandas as pd
data = [
    25,25,23,250,
    25,46,55
]
i = ["a","s","d","f","g","h","j"]
df=pd.Series(data , index =i)
print(df)

a     25
s     25
d     23
f    250
g     25
h     46
j     55
dtype: int64


In [194]:
my_dict = {
    "One" : 1,
    "Name": "Shubham"
}
df=pd.Series(my_dict)
df


One           1
Name    Shubham
dtype: object

In [196]:
my_dict["One"]

1

In [2]:
import pandas as pd
data = [
    25,25,23,250,
    25,46,55
]
df= pd.Series(data)
df.head(2)

0    25
1    25
dtype: int64

In [3]:
df.tail(2)

5    46
6    55
dtype: int64

In [4]:
df.describe()

count      7.000000
mean      64.142857
std       82.910451
min       23.000000
25%       25.000000
50%       25.000000
75%       50.500000
max      250.000000
dtype: float64

In [6]:
df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 7 entries, 0 to 6
Series name: None
Non-Null Count  Dtype
--------------  -----
7 non-null      int64
dtypes: int64(1)
memory usage: 188.0 bytes


In [7]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__column_consortium_standard__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__

In [11]:
print(df.index) 


RangeIndex(start=0, stop=7, step=1)


In [12]:
df = data+data
df

[25, 25, 23, 250, 25, 46, 55, 25, 25, 23, 250, 25, 46, 55]

In [13]:
import pandas as pd


s1 = pd.Series([10, 20, 30, 40])
s2 = pd.Series([5, 15, 25, 35])

result = s1 + s2

print(result)


0    15
1    35
2    55
3    75
dtype: int64


In [18]:
square = result.apply(lambda x : x**2)
square

0     225
1    1225
2    3025
3    5625
dtype: int64

In [19]:
square = result.sort_values()
square

0    15
1    35
2    55
3    75
dtype: int64

In [21]:
square = result.sort_values(ascending = False)
square

3    75
2    55
1    35
0    15
dtype: int64

In [28]:

square.isnull().sum()


0

In [30]:
square.isnull().sum()

0

In [31]:
square.sum()

180

In [33]:
df

[25, 25, 23, 250, 25, 46, 55, 25, 25, 23, 250, 25, 46, 55]

In [36]:
result.isnull().sum()

0

In [38]:
result.fillna(12)

0    15
1    35
2    55
3    75
dtype: int64

In [39]:
import pandas as pd


temp_series = pd.Series([100, 200, 300, 400, 500])

print(temp_series)


0    100
1    200
2    300
3    400
4    500
dtype: int64


In [65]:
import pandas as pd


temp_series = pd.Series([100, 200, 300, 400, 500,600,800])

days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday','Saturday',"Sunday"]
temp_series.index = days

print(temp_series)


Monday       100
Tuesday      200
Wednesday    300
Thursday     400
Friday       500
Saturday     600
Sunday       800
dtype: int64


In [49]:
temp_series['Tuesday'] = 250
print(temp_series)


Monday       100
Tuesday      250
Wednesday    300
Thursday     400
Friday       500
Saturday     600
Sunday       800
dtype: int64


In [50]:
temp_series = temp_series.drop("Wednesday")
print(temp_series)


Monday      100
Tuesday     250
Thursday    400
Friday      500
Saturday    600
Sunday      800
dtype: int64


In [72]:
average = temp_series.mean()
average

414.2857142857143

In [59]:
temp_series.max()


800

In [60]:
temp_series.idxmax()

'Sunday'

In [61]:
temp_series.idxmin()

'Monday'

In [75]:

threshold = 500 
significant_change_temp = temp_series[abs(temp_series ) > threshold]

print(significant_change_temp)


Saturday    600
Sunday      800
dtype: int64


In [76]:
#Data Framing 


In [77]:
#dictioneory
data = { "Name" : ["Shubham","Raj","Simran"],
        "Age" : [25,14,36],
        "Salary" : [225,364,485]
       }
df=pd.DataFrame(data)
df
    

Name  Age  Salary
0  Shubham   25     225
1      Raj   14     364
2   Simran   36     485

In [83]:
#list data set
my_list = [["Shubham",25,44],["Shuh",25,44],["S",25,44]]

df = pd.DataFrame(my_list,columns = [ "Name","Age","Salary"])
df



Name  Age  Salary
0  Shubham   25      44
1     Shuh   25      44
2        S   25      44

In [90]:
#Dtata Set NAme 
print("HousePrices.csv")
df =pd.read_csv("HousePrices.csv")
df.head(5)

HousePrices.csv


date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912   
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947   
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030   
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   
1     2.0           0     4          5        3370            280      1921   
2     1.0           0     0          4        1930              0      1966   
3     1.0           0     0          4        1000           1000      1963   
4     1.0           0     0          4        1140            800      1976   

   yr_renovated                    street       city  statezip country  
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA  
1             0           709 W Blaine St    Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA  
3             0           857 170th Pl NE   Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           4600 non-null   object 
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64  
 5   sqft_lot       4600 non-null   int64  
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64  
 8   view           4600 non-null   int64  
 9   condition      4600 non-null   int64  
 10  sqft_above     4600 non-null   int64  
 11  sqft_basement  4600 non-null   int64  
 12  yr_built       4600 non-null   int64  
 13  yr_renovated   4600 non-null   int64  
 14  street         4600 non-null   object 
 15  city           4600 non-null   object 
 16  statezip       4600 non-null   object 
 17  country        4600 non-null   object 
dtypes: float

In [92]:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [93]:
df.describe()

price     bedrooms    bathrooms   sqft_living      sqft_lot  \
count  4.600000e+03  4600.000000  4600.000000   4600.000000  4.600000e+03   
mean   5.519630e+05     3.400870     2.160815   2139.346957  1.485252e+04   
std    5.638347e+05     0.908848     0.783781    963.206916  3.588444e+04   
min    0.000000e+00     0.000000     0.000000    370.000000  6.380000e+02   
25%    3.228750e+05     3.000000     1.750000   1460.000000  5.000750e+03   
50%    4.609435e+05     3.000000     2.250000   1980.000000  7.683000e+03   
75%    6.549625e+05     4.000000     2.500000   2620.000000  1.100125e+04   
max    2.659000e+07     9.000000     8.000000  13540.000000  1.074218e+06   

            floors   waterfront         view    condition   sqft_above  \
count  4600.000000  4600.000000  4600.000000  4600.000000  4600.000000   
mean      1.512065     0.007174     0.240652     3.451739  1827.265435   
std       0.538288     0.084404     0.778405     0.677230   862.168977   
min       1.000000     0.000000     0.000000     1.000000   370.000000   
25%       1.000000     0.000000     0.000000     3.000000  1190.000000   
50%       1.500000     0.000000     0.000000     3.000000  1590.000000   
75%       2.000000     0.000000     0.000000     4.000000  2300.000000   
max       3.500000     1.000000     4.000000     5.000000  9410.000000   

       sqft_basement     yr_built  yr_renovated  
count    4600.000000  4600.000000   4600.000000  
mean      312.081522  1970.786304    808.608261  
std       464.137228    29.731848    979.414536  
min         0.000000  1900.000000      0.000000  
25%         0.000000  1951.000000      0.000000  
50%         0.000000  1976.000000      0.000000  
75%       610.000000  1997.000000   1999.000000  
max      4820.000000  2014.000000   2014.000000

In [94]:
df.tail(5)

date          price  bedrooms  bathrooms  sqft_living  \
4595  2014-07-09 00:00:00  308166.666667       3.0       1.75         1510   
4596  2014-07-09 00:00:00  534333.333333       3.0       2.50         1460   
4597  2014-07-09 00:00:00  416904.166667       3.0       2.50         3010   
4598  2014-07-10 00:00:00  203400.000000       4.0       2.00         2090   
4599  2014-07-10 00:00:00  220600.000000       3.0       2.50         1490   

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
4595      6360     1.0           0     0          4        1510   
4596      7573     2.0           0     0          3        1460   
4597      7014     2.0           0     0          3        3010   
4598      6630     1.0           0     0          3        1070   
4599      8102     2.0           0     0          4        1490   

      sqft_basement  yr_built  yr_renovated             street       city  \
4595              0      1954          1979     501 N 143rd St    Seattle   
4596              0      1983          2009   14855 SE 10th Pl   Bellevue   
4597              0      2009             0   759 Ilwaco Pl NE     Renton   
4598           1020      1974             0  5148 S Creston St    Seattle   
4599              0      1990             0  18717 SE 258th St  Covington   

      statezip country  
4595  WA 98133     USA  
4596  WA 98007     USA  
4597  WA 98059     USA  
4598  WA 98178     USA  
4599  WA 98042     USA

In [95]:
df.shape

(4600, 18)

In [96]:
df.isnull()

date  price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0     False  False     False      False        False     False   False   
1     False  False     False      False        False     False   False   
2     False  False     False      False        False     False   False   
3     False  False     False      False        False     False   False   
4     False  False     False      False        False     False   False   
...     ...    ...       ...        ...          ...       ...     ...   
4595  False  False     False      False        False     False   False   
4596  False  False     False      False        False     False   False   
4597  False  False     False      False        False     False   False   
4598  False  False     False      False        False     False   False   
4599  False  False     False      False        False     False   False   

      waterfront   view  condition  sqft_above  sqft_basement  yr_built  \
0          False  False      False       False          False     False   
1          False  False      False       False          False     False   
2          False  False      False       False          False     False   
3          False  False      False       False          False     False   
4          False  False      False       False          False     False   
...          ...    ...        ...         ...            ...       ...   
4595       False  False      False       False          False     False   
4596       False  False      False       False          False     False   
4597       False  False      False       False          False     False   
4598       False  False      False       False          False     False   
4599       False  False      False       False          False     False   

      yr_renovated  street   city  statezip  country  
0            False   False  False     False    False  
1            False   False  False     False    False  
2            False   False  False     False    False  
3            False   False  False     False    False  
4            False   False  False     False    False  
...            ...     ...    ...       ...      ...  
4595         False   False  False     False    False  
4596         False   False  False     False    False  
4597         False   False  False     False    False  
4598         False   False  False     False    False  
4599         False   False  False     False    False  

[4600 rows x 18 columns]

In [97]:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [98]:
df.sum()

date             2014-05-02 00:00:002014-05-02 00:00:002014-05-...
price                                            2539029746.976785
bedrooms                                                   15644.0
bathrooms                                                  9939.75
sqft_living                                                9840996
sqft_lot                                                  68321574
floors                                                      6955.5
waterfront                                                      33
view                                                          1107
condition                                                    15878
sqft_above                                                 8405421
sqft_basement                                              1435575
yr_built                                                   9065617
yr_renovated                                               3719598
street           18810 Densmore Ave N709 W Blaine St26206-2621

In [99]:
df.min()

date             2014-05-02 00:00:00
price                            0.0
bedrooms                         0.0
bathrooms                        0.0
sqft_living                      370
sqft_lot                         638
floors                           1.0
waterfront                         0
view                               0
condition                          1
sqft_above                       370
sqft_basement                      0
yr_built                        1900
yr_renovated                       0
street                  1 View Ln NE
city                          Algona
statezip                    WA 98001
country                          USA
dtype: object

In [100]:
df.max()

date             2014-07-10 00:00:00
price                     26590000.0
bedrooms                         9.0
bathrooms                        8.0
sqft_living                    13540
sqft_lot                     1074218
floors                           3.5
waterfront                         1
view                               4
condition                          5
sqft_above                      9410
sqft_basement                   4820
yr_built                        2014
yr_renovated                    2014
street             Valley View Trail
city                    Yarrow Point
statezip                    WA 98354
country                          USA
dtype: object

In [103]:
df.size

82800

In [104]:
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'street', 'city',
       'statezip', 'country'],
      dtype='object')

In [107]:
df['bedrooms'].head(12)

0     3.0
1     5.0
2     3.0
3     3.0
4     4.0
5     2.0
6     2.0
7     4.0
8     3.0
9     4.0
10    3.0
11    4.0
Name: bedrooms, dtype: float64

In [109]:
df[ 'bedrooms'].unique()

array([3., 5., 4., 2., 6., 7., 9., 1., 8., 0.])

In [110]:
df[ 'bedrooms'].nunique()

10

In [111]:
df[ 'bedrooms'].value_counts()

bedrooms
3.0    2032
4.0    1531
2.0     566
5.0     353
6.0      61
1.0      38
7.0      14
8.0       2
0.0       2
9.0       1
Name: count, dtype: int64

In [116]:
#for specifi c row acesses
df.iloc[0]

date              2014-05-02 00:00:00
price                        313000.0
bedrooms                          3.0
bathrooms                         1.5
sqft_living                      1340
sqft_lot                         7912
floors                            1.5
waterfront                          0
view                                0
condition                           3
sqft_above                       1340
sqft_basement                       0
yr_built                         1955
yr_renovated                     2005
street           18810 Densmore Ave N
city                        Shoreline
statezip                     WA 98133
country                           USA
Name: 0, dtype: object

In [120]:
df

date         price  bedrooms  bathrooms  sqft_living  \
0     2014-05-02 00:00:00  3.130000e+05       3.0       1.50         1340   
1     2014-05-02 00:00:00  2.384000e+06       5.0       2.50         3650   
2     2014-05-02 00:00:00  3.420000e+05       3.0       2.00         1930   
3     2014-05-02 00:00:00  4.200000e+05       3.0       2.25         2000   
4     2014-05-02 00:00:00  5.500000e+05       4.0       2.50         1940   
...                   ...           ...       ...        ...          ...   
4595  2014-07-09 00:00:00  3.081667e+05       3.0       1.75         1510   
4596  2014-07-09 00:00:00  5.343333e+05       3.0       2.50         1460   
4597  2014-07-09 00:00:00  4.169042e+05       3.0       2.50         3010   
4598  2014-07-10 00:00:00  2.034000e+05       4.0       2.00         2090   
4599  2014-07-10 00:00:00  2.206000e+05       3.0       2.50         1490   

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
0         7912     1.5           0     0          3        1340   
1         9050     2.0           0     4          5        3370   
2        11947     1.0           0     0          4        1930   
3         8030     1.0           0     0          4        1000   
4        10500     1.0           0     0          4        1140   
...        ...     ...         ...   ...        ...         ...   
4595      6360     1.0           0     0          4        1510   
4596      7573     2.0           0     0          3        1460   
4597      7014     2.0           0     0          3        3010   
4598      6630     1.0           0     0          3        1070   
4599      8102     2.0           0     0          4        1490   

      sqft_basement  yr_built  yr_renovated                    street  \
0                 0      1955          2005      18810 Densmore Ave N   
1               280      1921             0           709 W Blaine St   
2                 0      1966             0  26206-26214 143rd Ave SE   
3              1000      1963             0           857 170th Pl NE   
4               800      1976          1992         9105 170th Ave NE   
...             ...       ...           ...                       ...   
4595              0      1954          1979            501 N 143rd St   
4596              0      1983          2009          14855 SE 10th Pl   
4597              0      2009             0          759 Ilwaco Pl NE   
4598           1020      1974             0         5148 S Creston St   
4599              0      1990             0         18717 SE 258th St   

           city  statezip country  
0     Shoreline  WA 98133     USA  
1       Seattle  WA 98119     USA  
2          Kent  WA 98042     USA  
3      Bellevue  WA 98008     USA  
4       Redmond  WA 98052     USA  
...         ...       ...     ...  
4595    Seattle  WA 98133     USA  
4596   Bellevue  WA 98007     USA  
4597     Renton  WA 98059     USA  
4598    Seattle  WA 98178     USA  
4599  Covington  WA 98042     USA  

[4600 rows x 18 columns]

In [128]:
df[df['bedrooms']<100]

date         price  bedrooms  bathrooms  sqft_living  \
0     2014-05-02 00:00:00  3.130000e+05       3.0       1.50         1340   
1     2014-05-02 00:00:00  2.384000e+06       5.0       2.50         3650   
2     2014-05-02 00:00:00  3.420000e+05       3.0       2.00         1930   
3     2014-05-02 00:00:00  4.200000e+05       3.0       2.25         2000   
4     2014-05-02 00:00:00  5.500000e+05       4.0       2.50         1940   
...                   ...           ...       ...        ...          ...   
4595  2014-07-09 00:00:00  3.081667e+05       3.0       1.75         1510   
4596  2014-07-09 00:00:00  5.343333e+05       3.0       2.50         1460   
4597  2014-07-09 00:00:00  4.169042e+05       3.0       2.50         3010   
4598  2014-07-10 00:00:00  2.034000e+05       4.0       2.00         2090   
4599  2014-07-10 00:00:00  2.206000e+05       3.0       2.50         1490   

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
0         7912     1.5           0     0          3        1340   
1         9050     2.0           0     4          5        3370   
2        11947     1.0           0     0          4        1930   
3         8030     1.0           0     0          4        1000   
4        10500     1.0           0     0          4        1140   
...        ...     ...         ...   ...        ...         ...   
4595      6360     1.0           0     0          4        1510   
4596      7573     2.0           0     0          3        1460   
4597      7014     2.0           0     0          3        3010   
4598      6630     1.0           0     0          3        1070   
4599      8102     2.0           0     0          4        1490   

      sqft_basement  yr_built  yr_renovated                    street  \
0                 0      1955          2005      18810 Densmore Ave N   
1               280      1921             0           709 W Blaine St   
2                 0      1966             0  26206-26214 143rd Ave SE   
3              1000      1963             0           857 170th Pl NE   
4               800      1976          1992         9105 170th Ave NE   
...             ...       ...           ...                       ...   
4595              0      1954          1979            501 N 143rd St   
4596              0      1983          2009          14855 SE 10th Pl   
4597              0      2009             0          759 Ilwaco Pl NE   
4598           1020      1974             0         5148 S Creston St   
4599              0      1990             0         18717 SE 258th St   

           city  statezip country  
0     Shoreline  WA 98133     USA  
1       Seattle  WA 98119     USA  
2          Kent  WA 98042     USA  
3      Bellevue  WA 98008     USA  
4       Redmond  WA 98052     USA  
...         ...       ...     ...  
4595    Seattle  WA 98133     USA  
4596   Bellevue  WA 98007     USA  
4597     Renton  WA 98059     USA  
4598    Seattle  WA 98178     USA  
4599  Covington  WA 98042     USA  

[4600 rows x 18 columns]

In [131]:
df.iat[1,2]

5.0

In [ ]:
df.at["Bedroom"]

In [143]:
df.iat[2,15]

'Kent'

In [144]:
df.describe()

price     bedrooms    bathrooms   sqft_living      sqft_lot  \
count  4.600000e+03  4600.000000  4600.000000   4600.000000  4.600000e+03   
mean   5.519630e+05     3.400870     2.160815   2139.346957  1.485252e+04   
std    5.638347e+05     0.908848     0.783781    963.206916  3.588444e+04   
min    0.000000e+00     0.000000     0.000000    370.000000  6.380000e+02   
25%    3.228750e+05     3.000000     1.750000   1460.000000  5.000750e+03   
50%    4.609435e+05     3.000000     2.250000   1980.000000  7.683000e+03   
75%    6.549625e+05     4.000000     2.500000   2620.000000  1.100125e+04   
max    2.659000e+07     9.000000     8.000000  13540.000000  1.074218e+06   

            floors   waterfront         view    condition   sqft_above  \
count  4600.000000  4600.000000  4600.000000  4600.000000  4600.000000   
mean      1.512065     0.007174     0.240652     3.451739  1827.265435   
std       0.538288     0.084404     0.778405     0.677230   862.168977   
min       1.000000     0.000000     0.000000     1.000000   370.000000   
25%       1.000000     0.000000     0.000000     3.000000  1190.000000   
50%       1.500000     0.000000     0.000000     3.000000  1590.000000   
75%       2.000000     0.000000     0.000000     4.000000  2300.000000   
max       3.500000     1.000000     4.000000     5.000000  9410.000000   

       sqft_basement     yr_built  yr_renovated  
count    4600.000000  4600.000000   4600.000000  
mean      312.081522  1970.786304    808.608261  
std       464.137228    29.731848    979.414536  
min         0.000000  1900.000000      0.000000  
25%         0.000000  1951.000000      0.000000  
50%         0.000000  1976.000000      0.000000  
75%       610.000000  1997.000000   1999.000000  
max      4820.000000  2014.000000   2014.000000

In [150]:
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'street', 'city',
       'statezip', 'country'],
      dtype='object')

In [ ]:
#Correlation
df.corr()

In [163]:
df[ ['waterfront', 'view','condition']].corr()

waterfront      view  condition
waterfront    1.000000  0.360935   0.000352
view          0.360935  1.000000   0.063077
condition     0.000352  0.063077   1.000000

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           4600 non-null   object 
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64  
 5   sqft_lot       4600 non-null   int64  
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64  
 8   view           4600 non-null   int64  
 9   condition      4600 non-null   int64  
 10  sqft_above     4600 non-null   int64  
 11  sqft_basement  4600 non-null   int64  
 12  yr_built       4600 non-null   int64  
 13  yr_renovated   4600 non-null   int64  
 14  street         4600 non-null   object 
 15  city           4600 non-null   object 
 16  statezip       4600 non-null   object 
 17  country        4600 non-null   object 
dtypes: float

In [164]:
df.drop(0)

date         price  bedrooms  bathrooms  sqft_living  \
1     2014-05-02 00:00:00  2.384000e+06       5.0       2.50         3650   
2     2014-05-02 00:00:00  3.420000e+05       3.0       2.00         1930   
3     2014-05-02 00:00:00  4.200000e+05       3.0       2.25         2000   
4     2014-05-02 00:00:00  5.500000e+05       4.0       2.50         1940   
5     2014-05-02 00:00:00  4.900000e+05       2.0       1.00          880   
...                   ...           ...       ...        ...          ...   
4595  2014-07-09 00:00:00  3.081667e+05       3.0       1.75         1510   
4596  2014-07-09 00:00:00  5.343333e+05       3.0       2.50         1460   
4597  2014-07-09 00:00:00  4.169042e+05       3.0       2.50         3010   
4598  2014-07-10 00:00:00  2.034000e+05       4.0       2.00         2090   
4599  2014-07-10 00:00:00  2.206000e+05       3.0       2.50         1490   

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
1         9050     2.0           0     4          5        3370   
2        11947     1.0           0     0          4        1930   
3         8030     1.0           0     0          4        1000   
4        10500     1.0           0     0          4        1140   
5         6380     1.0           0     0          3         880   
...        ...     ...         ...   ...        ...         ...   
4595      6360     1.0           0     0          4        1510   
4596      7573     2.0           0     0          3        1460   
4597      7014     2.0           0     0          3        3010   
4598      6630     1.0           0     0          3        1070   
4599      8102     2.0           0     0          4        1490   

      sqft_basement  yr_built  yr_renovated                    street  \
1               280      1921             0           709 W Blaine St   
2                 0      1966             0  26206-26214 143rd Ave SE   
3              1000      1963             0           857 170th Pl NE   
4               800      1976          1992         9105 170th Ave NE   
5                 0      1938          1994            522 NE 88th St   
...             ...       ...           ...                       ...   
4595              0      1954          1979            501 N 143rd St   
4596              0      1983          2009          14855 SE 10th Pl   
4597              0      2009             0          759 Ilwaco Pl NE   
4598           1020      1974             0         5148 S Creston St   
4599              0      1990             0         18717 SE 258th St   

           city  statezip country  
1       Seattle  WA 98119     USA  
2          Kent  WA 98042     USA  
3      Bellevue  WA 98008     USA  
4       Redmond  WA 98052     USA  
5       Seattle  WA 98115     USA  
...         ...       ...     ...  
4595    Seattle  WA 98133     USA  
4596   Bellevue  WA 98007     USA  
4597     Renton  WA 98059     USA  
4598    Seattle  WA 98178     USA  
4599  Covington  WA 98042     USA  

[4599 rows x 18 columns]

In [165]:
df

date         price  bedrooms  bathrooms  sqft_living  \
0     2014-05-02 00:00:00  3.130000e+05       3.0       1.50         1340   
1     2014-05-02 00:00:00  2.384000e+06       5.0       2.50         3650   
2     2014-05-02 00:00:00  3.420000e+05       3.0       2.00         1930   
3     2014-05-02 00:00:00  4.200000e+05       3.0       2.25         2000   
4     2014-05-02 00:00:00  5.500000e+05       4.0       2.50         1940   
...                   ...           ...       ...        ...          ...   
4595  2014-07-09 00:00:00  3.081667e+05       3.0       1.75         1510   
4596  2014-07-09 00:00:00  5.343333e+05       3.0       2.50         1460   
4597  2014-07-09 00:00:00  4.169042e+05       3.0       2.50         3010   
4598  2014-07-10 00:00:00  2.034000e+05       4.0       2.00         2090   
4599  2014-07-10 00:00:00  2.206000e+05       3.0       2.50         1490   

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
0         7912     1.5           0     0          3        1340   
1         9050     2.0           0     4          5        3370   
2        11947     1.0           0     0          4        1930   
3         8030     1.0           0     0          4        1000   
4        10500     1.0           0     0          4        1140   
...        ...     ...         ...   ...        ...         ...   
4595      6360     1.0           0     0          4        1510   
4596      7573     2.0           0     0          3        1460   
4597      7014     2.0           0     0          3        3010   
4598      6630     1.0           0     0          3        1070   
4599      8102     2.0           0     0          4        1490   

      sqft_basement  yr_built  yr_renovated                    street  \
0                 0      1955          2005      18810 Densmore Ave N   
1               280      1921             0           709 W Blaine St   
2                 0      1966             0  26206-26214 143rd Ave SE   
3              1000      1963             0           857 170th Pl NE   
4               800      1976          1992         9105 170th Ave NE   
...             ...       ...           ...                       ...   
4595              0      1954          1979            501 N 143rd St   
4596              0      1983          2009          14855 SE 10th Pl   
4597              0      2009             0          759 Ilwaco Pl NE   
4598           1020      1974             0         5148 S Creston St   
4599              0      1990             0         18717 SE 258th St   

           city  statezip country  
0     Shoreline  WA 98133     USA  
1       Seattle  WA 98119     USA  
2          Kent  WA 98042     USA  
3      Bellevue  WA 98008     USA  
4       Redmond  WA 98052     USA  
...         ...       ...     ...  
4595    Seattle  WA 98133     USA  
4596   Bellevue  WA 98007     USA  
4597     Renton  WA 98059     USA  
4598    Seattle  WA 98178     USA  
4599  Covington  WA 98042     USA  

[4600 rows x 18 columns]

In [166]:
df.drop("bedrooms",axis =1)

date         price  bathrooms  sqft_living  sqft_lot  \
0     2014-05-02 00:00:00  3.130000e+05       1.50         1340      7912   
1     2014-05-02 00:00:00  2.384000e+06       2.50         3650      9050   
2     2014-05-02 00:00:00  3.420000e+05       2.00         1930     11947   
3     2014-05-02 00:00:00  4.200000e+05       2.25         2000      8030   
4     2014-05-02 00:00:00  5.500000e+05       2.50         1940     10500   
...                   ...           ...        ...          ...       ...   
4595  2014-07-09 00:00:00  3.081667e+05       1.75         1510      6360   
4596  2014-07-09 00:00:00  5.343333e+05       2.50         1460      7573   
4597  2014-07-09 00:00:00  4.169042e+05       2.50         3010      7014   
4598  2014-07-10 00:00:00  2.034000e+05       2.00         2090      6630   
4599  2014-07-10 00:00:00  2.206000e+05       2.50         1490      8102   

      floors  waterfront  view  condition  sqft_above  sqft_basement  \
0        1.5           0     0          3        1340              0   
1        2.0           0     4          5        3370            280   
2        1.0           0     0          4        1930              0   
3        1.0           0     0          4        1000           1000   
4        1.0           0     0          4        1140            800   
...      ...         ...   ...        ...         ...            ...   
4595     1.0           0     0          4        1510              0   
4596     2.0           0     0          3        1460              0   
4597     2.0           0     0          3        3010              0   
4598     1.0           0     0          3        1070           1020   
4599     2.0           0     0          4        1490              0   

      yr_built  yr_renovated                    street       city  statezip  \
0         1955          2005      18810 Densmore Ave N  Shoreline  WA 98133   
1         1921             0           709 W Blaine St    Seattle  WA 98119   
2         1966             0  26206-26214 143rd Ave SE       Kent  WA 98042   
3         1963             0           857 170th Pl NE   Bellevue  WA 98008   
4         1976          1992         9105 170th Ave NE    Redmond  WA 98052   
...        ...           ...                       ...        ...       ...   
4595      1954          1979            501 N 143rd St    Seattle  WA 98133   
4596      1983          2009          14855 SE 10th Pl   Bellevue  WA 98007   
4597      2009             0          759 Ilwaco Pl NE     Renton  WA 98059   
4598      1974             0         5148 S Creston St    Seattle  WA 98178   
4599      1990             0         18717 SE 258th St  Covington  WA 98042   

     country  
0        USA  
1        USA  
2        USA  
3        USA  
4        USA  
...      ...  
4595     USA  
4596     USA  
4597     USA  
4598     USA  
4599     USA  

[4600 rows x 17 columns]

In [168]:
df.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912   
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947   
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030   
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   
1     2.0           0     4          5        3370            280      1921   
2     1.0           0     0          4        1930              0      1966   
3     1.0           0     0          4        1000           1000      1963   
4     1.0           0     0          4        1140            800      1976   

   yr_renovated                    street       city  statezip country  
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA  
1             0           709 W Blaine St    Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA  
3             0           857 170th Pl NE   Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [ ]:
df.drop("bedrooms",axis =1,inplace=True)

In [174]:
df.head()

date      price  bathrooms  sqft_living  sqft_lot  floors  \
0  2014-05-02 00:00:00   313000.0       1.50         1340      7912     1.5   
1  2014-05-02 00:00:00  2384000.0       2.50         3650      9050     2.0   
2  2014-05-02 00:00:00   342000.0       2.00         1930     11947     1.0   
3  2014-05-02 00:00:00   420000.0       2.25         2000      8030     1.0   
4  2014-05-02 00:00:00   550000.0       2.50         1940     10500     1.0   

   waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0           0     0          3        1340              0      1955   
1           0     4          5        3370            280      1921   
2           0     0          4        1930              0      1966   
3           0     0          4        1000           1000      1963   
4           0     0          4        1140            800      1976   

   yr_renovated                    street       city  statezip country  
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA  
1             0           709 W Blaine St    Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA  
3             0           857 170th Pl NE   Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [179]:
df.dropna()

date         price  bathrooms  sqft_living  sqft_lot  \
0     2014-05-02 00:00:00  3.130000e+05       1.50         1340      7912   
1     2014-05-02 00:00:00  2.384000e+06       2.50         3650      9050   
2     2014-05-02 00:00:00  3.420000e+05       2.00         1930     11947   
3     2014-05-02 00:00:00  4.200000e+05       2.25         2000      8030   
4     2014-05-02 00:00:00  5.500000e+05       2.50         1940     10500   
...                   ...           ...        ...          ...       ...   
4595  2014-07-09 00:00:00  3.081667e+05       1.75         1510      6360   
4596  2014-07-09 00:00:00  5.343333e+05       2.50         1460      7573   
4597  2014-07-09 00:00:00  4.169042e+05       2.50         3010      7014   
4598  2014-07-10 00:00:00  2.034000e+05       2.00         2090      6630   
4599  2014-07-10 00:00:00  2.206000e+05       2.50         1490      8102   

      floors  waterfront  view  condition  sqft_above  sqft_basement  \
0        1.5           0     0          3        1340              0   
1        2.0           0     4          5        3370            280   
2        1.0           0     0          4        1930              0   
3        1.0           0     0          4        1000           1000   
4        1.0           0     0          4        1140            800   
...      ...         ...   ...        ...         ...            ...   
4595     1.0           0     0          4        1510              0   
4596     2.0           0     0          3        1460              0   
4597     2.0           0     0          3        3010              0   
4598     1.0           0     0          3        1070           1020   
4599     2.0           0     0          4        1490              0   

      yr_built  yr_renovated                    street       city  statezip  \
0         1955          2005      18810 Densmore Ave N  Shoreline  WA 98133   
1         1921             0           709 W Blaine St    Seattle  WA 98119   
2         1966             0  26206-26214 143rd Ave SE       Kent  WA 98042   
3         1963             0           857 170th Pl NE   Bellevue  WA 98008   
4         1976          1992         9105 170th Ave NE    Redmond  WA 98052   
...        ...           ...                       ...        ...       ...   
4595      1954          1979            501 N 143rd St    Seattle  WA 98133   
4596      1983          2009          14855 SE 10th Pl   Bellevue  WA 98007   
4597      2009             0          759 Ilwaco Pl NE     Renton  WA 98059   
4598      1974             0         5148 S Creston St    Seattle  WA 98178   
4599      1990             0         18717 SE 258th St  Covington  WA 98042   

     country  
0        USA  
1        USA  
2        USA  
3        USA  
4        USA  
...      ...  
4595     USA  
4596     USA  
4597     USA  
4598     USA  
4599     USA  

[4600 rows x 17 columns]

In [180]:
import datetime as datetime

In [196]:
from datetime import datetime,
now = datetime.now()
print(now)



2025-06-10 15:47:15.356727


In [203]:
today = now.date()
print(today)  

2025-06-10


In [202]:
from datetime import datetime, timedelta


today = datetime.today().date()


future_date = today + timedelta(days=6)

print(future_date)


2025-06-16


In [204]:
#Creating the range
date_range = pd.date_range(start = "2025-06-16",end ="2025-12-16",freq = "MS")
date_range

DatetimeIndex(['2025-07-01', '2025-08-01', '2025-09-01', '2025-10-01',
               '2025-11-01', '2025-12-01'],
              dtype='datetime64[ns]', freq='MS')

In [206]:
#Creating the range
date_range = pd.date_range(start = "2025-06-16",end ="2025-7-16")
date_range

DatetimeIndex(['2025-06-16', '2025-06-17', '2025-06-18', '2025-06-19',
               '2025-06-20', '2025-06-21', '2025-06-22', '2025-06-23',
               '2025-06-24', '2025-06-25', '2025-06-26', '2025-06-27',
               '2025-06-28', '2025-06-29', '2025-06-30', '2025-07-01',
               '2025-07-02', '2025-07-03', '2025-07-04', '2025-07-05',
               '2025-07-06', '2025-07-07', '2025-07-08', '2025-07-09',
               '2025-07-10', '2025-07-11', '2025-07-12', '2025-07-13',
               '2025-07-14', '2025-07-15', '2025-07-16'],
              dtype='datetime64[ns]', freq='D')

In [239]:
df = pd.DataFrame(date_range)


In [249]:
df.head()

Date  Day  Month  Year
0 2025-06-16   16      6     6
1 2025-06-17   17      6     6
2 2025-06-18   18      6     6
3 2025-06-19   19      6     6
4 2025-06-20   20      6     6

In [243]:
df["Date"] = df[0]

In [244]:
df.drop(0,axis =1,inplace=True)

In [250]:
df["Day"] = df["Date"].dt.day
df["Month"] = df["Date"].dt.month
df["Year"] = df["Date"].dt.month
df["Weekend"] = df["Date"].dt.weekday.isin([5, 6])
df.head(5)

Date  Day  Month  Year  Weekend
0 2025-06-16   16      6     6    False
1 2025-06-17   17      6     6    False
2 2025-06-18   18      6     6    False
3 2025-06-19   19      6     6    False
4 2025-06-20   20      6     6    False

In [2]:
import pandas as pd
import numpy as np


data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}

df = pd.DataFrame(data)

df


Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

In [269]:
df.isnull().sum()

Energy Source               0
Energy Consumption (MWh)    2
Cost (Million $)            2
dtype: int64

In [271]:
df.drop("Energy Consumption (MWh)" ,axis=1,inplace=True)

In [262]:
df.isnull().sum()

Energy Source       0
Cost (Million $)    2
dtype: int64

In [263]:
df.isnull().sum()

Energy Source       0
Cost (Million $)    2
dtype: int64

In [270]:
df.drop("Cost (Million $)" ,axis=1,inplace=True)

In [265]:
df.isnull().sum()

Energy Source    0
dtype: int64

In [274]:
df

Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

In [275]:
df.dropna()

Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
4       Biomass                    2500.0             250.0

In [3]:
df

Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

In [4]:
df.dropna()

Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
4       Biomass                    2500.0             250.0

In [7]:
df["Energy Source"]

0         Solar
1          Wind
2    Hydropower
3    Geothermal
4       Biomass
5       Nuclear
Name: Energy Source, dtype: object

In [8]:
df["Energy Consumption (MWh)"]

0    1200.0
1       NaN
2    2900.0
3       NaN
4    2500.0
5    3200.0
Name: Energy Consumption (MWh), dtype: float64

In [9]:
#energy_consumption.CSV

SyntaxError: invalid non-printable character U+00A0 (644024562.py, line 8)