In [1]:
!pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [5]:
#Scalar One dimentional array
array_0 = np.array(2)
print(array_01)

2


In [6]:
array_0.ndim

0

In [8]:
#one dimentional array
array_01=np.array([1,2,3,6,45,9])
print(array_01)

[ 1  2  3  6 45  9]


In [11]:
array_01.ndim

1

In [23]:
#two dimenstiona;l array
array_02 = np.array([[1,2,3,6,45,9],
                     [1,2,3,6,45,9]])
print(array_02)

[[ 1  2  3  6 45  9]
 [ 1  2  3  6 45  9]]


In [18]:
array_02.ndim

2

In [30]:
import numpy as np

# 
array_03 = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],  
    [[13, 14, 15], [16, 17, 18]]  
    
])

print(array_03)
print(array_03.ndim)  # Output: 3


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
3


In [31]:
import numpy as np

array_4d = np.array([
    [
        [[1, 2], [3, 4]], [[5, 6], [7, 8]]
    ],
    [
        [[9, 10], [11, 12]], [[13, 14], [15, 16]]
    ]
])

print(array_4d)
print("Number of dimensions:", array_4d.ndim)


[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
Number of dimensions: 4


In [38]:

array_d = np.array([[30, 32, 31, 29, 28], [27, 29, 28, 26, 25]]) 

transposed = array_d.T
flattened = array_d.flatten()
reshaped = array_d.reshape(5, 2)

print("Original Array:\n", array_d)
print("\nTransposed:\n", transposed)
print("\nFlattened:\n", flattened)
print("\nReshaped (5x2):\n", reshaped)


Original Array:
 [[30 32 31 29 28]
 [27 29 28 26 25]]

Transposed:
 [[30 27]
 [32 29]
 [31 28]
 [29 26]
 [28 25]]

Flattened:
 [30 32 31 29 28 27 29 28 26 25]

Reshaped (5x2):
 [[30 32]
 [31 29]
 [28 27]
 [29 28]
 [26 25]]


In [43]:
array_d.shape

(2, 5)

In [47]:
array_d.reshape(5,2)

array([[30, 32],
       [31, 29],
       [28, 27],
       [29, 28],
       [26, 25]])

In [48]:
array_d.flatten()

array([30, 32, 31, 29, 28, 27, 29, 28, 26, 25])

In [51]:
array_d.T

array([[30, 27],
       [32, 29],
       [31, 28],
       [29, 26],
       [28, 25]])

In [52]:
array_d1 =([30, 32, 31, 29, 28, 27, 29, 28, 26, 25]) 
print(array_d1 )

[30, 32, 31, 29, 28, 27, 29, 28, 26, 25]


In [53]:
array_d1 =([30, 32, 31, 29, 28, 27, 29, 28, 26, 25]) 
array_d2 =([30, 32, 31, 29, 28, 27, 29, 28, 26, 25]) 
add = np.add(array_d1,array_d1)
print(add)

[60 64 62 58 56 54 58 56 52 50]


In [55]:
array_d1 =([30, 32, 31, 29, 28, 27, 29, 28, 26, 25]) 
array_d2 =([30, 32, 31, 29, 28, 27, 29, 28, 26, 25]) 
add = np.divide(array_d1,array_d1)
print(add)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [57]:
array_d1 =([30, 32, 31, 29, 28, 27, 29, 28, 26, 25]) 
array_d2 =([30, 32, 31, 29, 28, 27, 29, 28, 26, 25]) 
add = np.multiply(array_d1,array_d1)
print(add)

[ 900 1024  961  841  784  729  841  784  676  625]


In [59]:
array_d1 =([30, 32, 31, 29, 28, 27, 29, 28, 26, 25]) 
array_d2 =([30, 32, 31, 29, 28, 27, 29, 28, 26, 25]) 
add = np.subtract(array_d1,array_d1)
print(add)

[0 0 0 0 0 0 0 0 0 0]


In [63]:
array_d1 =([30, 32, 31]) 
array_d2 =([30, 32, 31]) 
add = np.power(array_d1,array_d1)
print(add)

[ 1073741824           0 -2010103841]


In [76]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [81]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

##### a.shape

In [79]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [88]:
np.arange(8,20,2).reshape(3,2)

array([[ 8, 10],
       [12, 14],
       [16, 18]])

In [89]:
np.arange(8,20,2)

array([ 8, 10, 12, 14, 16, 18])

In [92]:
np.linspace(10,20,100)

array([10.        , 10.1010101 , 10.2020202 , 10.3030303 , 10.4040404 ,
       10.50505051, 10.60606061, 10.70707071, 10.80808081, 10.90909091,
       11.01010101, 11.11111111, 11.21212121, 11.31313131, 11.41414141,
       11.51515152, 11.61616162, 11.71717172, 11.81818182, 11.91919192,
       12.02020202, 12.12121212, 12.22222222, 12.32323232, 12.42424242,
       12.52525253, 12.62626263, 12.72727273, 12.82828283, 12.92929293,
       13.03030303, 13.13131313, 13.23232323, 13.33333333, 13.43434343,
       13.53535354, 13.63636364, 13.73737374, 13.83838384, 13.93939394,
       14.04040404, 14.14141414, 14.24242424, 14.34343434, 14.44444444,
       14.54545455, 14.64646465, 14.74747475, 14.84848485, 14.94949495,
       15.05050505, 15.15151515, 15.25252525, 15.35353535, 15.45454545,
       15.55555556, 15.65656566, 15.75757576, 15.85858586, 15.95959596,
       16.06060606, 16.16161616, 16.26262626, 16.36363636, 16.46464646,
       16.56565657, 16.66666667, 16.76767677, 16.86868687, 16.96

In [95]:
x = np.linspace(0,2*2,10)
print(x)

[0.         0.44444444 0.88888889 1.33333333 1.77777778 2.22222222
 2.66666667 3.11111111 3.55555556 4.        ]


In [96]:
np.sin(x)

array([ 0.        ,  0.42995636,  0.77637192,  0.9719379 ,  0.9786557 ,
        0.79522006,  0.45727263,  0.03047682, -0.40224065, -0.7568025 ])

In [98]:
#statical Operatio
a=np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [105]:
np.mean(a)


7.0

In [106]:
np.median(a)

7.0

In [107]:
np.std(a)

4.320493798938574

In [108]:
np.var(a)

18.666666666666668

In [111]:
np.percentile(a,10)

1.4000000000000001

In [113]:
import numpy as np

# Define arrays
A = np.array([15, 25, 35, 45, 55])
B = np.array([5, 10, 15, 20, 25])
C = np.array([12, 22, 32, 42, 52, 62, 72, 82, 92, 102])

# String arrays using NumPy
X = np.array(['Hello', 'Data', 'Science', 'Class', 'Learners'])
Y = np.array(['World', 'Analysis', 'is', 'Fun', '2023'])

# Arithmetic operations
addition = np.add(A, B)
subtraction = np.subtract(A, B)
multiplication = np.multiply(A, B)
division = np.divide(A, B)
power = np.power(A, B)

# Statistical operations
median_value = np.median(C)
mean_value = np.mean(C)
std_dev = np.std(C)
variance_value = np.var(C)

# String operations
concatenation = np.char.add(X, Y)  # Element-wise concatenation
uppercase_X = np.char.upper(X)  # Convert to uppercase
modified_Y = np.char.replace(Y, "Fun", "Exciting")  # Replace "Fun" with "Exciting"

# Print results
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)
print("Power:", power)

print("\nMedian:", median_value)
print("Mean:", mean_value)
print("Standard Deviation:", std_dev)
print("Variance:", variance_value)

print("\nConcatenated Strings:", concatenation)
print("Uppercase X:", uppercase_X)
print("Modified Y:", modified_Y)


Addition: [20 35 50 65 80]
Subtraction: [10 15 20 25 30]
Multiplication: [  75  250  525  900 1375]
Division: [3.         2.5        2.33333333 2.25       2.2       ]
Power: [     759375  1977800241 -2091638453 -1924594607   447042167]

Median: 57.0
Mean: 57.0
Standard Deviation: 28.722813232690143
Variance: 825.0

Concatenated Strings: ['HelloWorld' 'DataAnalysis' 'Scienceis' 'ClassFun' 'Learners2023']
Uppercase X: ['HELLO' 'DATA' 'SCIENCE' 'CLASS' 'LEARNERS']
Modified Y: ['World' 'Analysis' 'is' 'Exciting' '2023']


In [114]:
import numpy as np


array_1d = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("1D Array:\n", array_1d)


array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("\n2D Array:\n", array_2d)


array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print("\n3D Array:\n", array_3d)

print("\nAccessing Elements:")
print("1D Array element at index 2:", array_1d[2])
print("2D Array element at row 1, column 2:", array_2d[1, 2])
print("3D Array element at matrix 1, row 0, column 2:", array_3d[1, 0, 2])


add_result = array_1d[0] + array_2d[1, 2] + array_3d[1, 0, 2]
sub_result = array_1d[0] - array_2d[1, 2] - array_3d[1, 0, 2]

print("\nArithmetic Operations:")
print("Addition:", add_result)
print("Subtraction:", sub_result)


print("\nNegative Indexing:")
print("Last element of 1D Array:", array_1d[-1])
print("Last row, last column of 2D Array:", array_2d[-1, -1])
print("Last matrix, last row, last column of 3D Array:", array_3d[-1, -1, -1])


1D Array:
 [ 10  20  30  40  50  60  70  80  90 100]

2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Accessing Elements:
1D Array element at index 2: 30
2D Array element at row 1, column 2: 7
3D Array element at matrix 1, row 0, column 2: 9

Arithmetic Operations:
Addition: 26
Subtraction: -6

Negative Indexing:
Last element of 1D Array: 100
Last row, last column of 2D Array: 12
Last matrix, last row, last column of 3D Array: 12
